name: Angular CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      name: Checkout code
    - name: Use Node.js 20.10.0
      uses: actions/setup-node@v3
      with:
        node-version: 20.10.0
        cache: 'npm'
    - run: npm install --force
    - run: npm install @angular/cli --force
    - run: npm run build
    - run: npm run start
